illinois-ceesd/emirge

install-conda-dependencies.sh
=> install islpy with conda

install-conda-dependencies.sh
=> install-conda-dependencies.sh: do not modify .bashrc

install-pip-dependencies.sh
=> pip: remove --user

.github/workflows/tests.yaml, version.sh
Fixes #21.
Output can be seen here: 
- https://github.com/illinois-ceesd/emirge/pull/30/checks?check_run_id=751193900 (Linux)
- https://github.com/illinois-ceesd/emirge/pull/30/checks?check_run_id=751193852 (MacOS)
=> Version info script

README.md
=> debashify README

README.md
Closes https://github.com/illinois-ceesd/planning/issues/26.
Addresses a comment made here: https://github.com/illinois-ceesd/emirge/pull/35
=> README: document installation script

install-conda.sh
=> conda: make sure to install even if directory already exists

.github/workflows/makezip.yaml, .github/workflows/tests.yaml, install-conda-dependencies.sh
=> Install MPI if not already available

install-pip-dependencies.sh
Context: https://github.com/illinois-ceesd/mirgecom/pull/43
=> Work around pip breakage in install.sh

install.sh, parse_requirements.sh
Specify which branch of mirgecom to build.
=> add --branch option

install-conda-dependencies.sh
Fixes https://github.com/illinois-ceesd/mirgecom/issues/50
=> Use POCL-CUDA instead of POCL

.github/workflows/makezip.yaml, .github/workflows/tests.yaml, install.sh
=> Default to installing miniforge under emirge

.gitignore
=> ignore conda install dir

install-conda-dependencies.sh
Package is now available for Power9.
=> Install clinfo for everyone

version.sh
- fix loopy printing
- show date of HEAD commit
- show branch name if no specified
- show dirty state
=> version.sh: various fixes

README.md
=> explain file formats

.github/workflows/tests.yaml, install.sh, version.sh
Fixes #90.
Doc is here: https://github.com/illinois-ceesd/mirgecom/pull/148
=> create conda env file in versions.sh

install-conda-dependencies.sh, install-pip-dependencies.sh
=> install pymetis via conda

version.sh
=> Redirect output via 'tee'

install-pip-dependencies.sh
=> error out when trying to build mpi4py with XL

install-pip-dependencies.sh
Exposed by https://github.com/illinois-ceesd/mirgecom/pull/248
insert <facepalm.jpg> here
=> change to folder before attempting to checkout new branch

install.sh
Closes #114 through workaround
=> install clang_osx-64

version.sh
when not creating a file with output, tee was trying to write to `..`.
=> version.sh: fix output of requirements file

version.sh
- remove unnecessary branch determination
- make sure to always store commit
- remove extra `\` in URL
=> version.sh: clean up branch behavior

README.md, fetch-mirgecom.sh, install.sh
=> rename mirgecom's master branch to main

install-conda.sh, install.sh
=> Apple M1 fixes

pull-packages.sh
=> reactivate conda update in pull-packages

install-pip-dependencies.sh
x-ref: https://github.com/illinois-ceesd/mirgecom/pull/336
=> Install flake8-bugbear in install-pip-dependencies.sh

install-conda.sh
https://github.com/conda-forge/miniforge/pull/156
cc @isuruf
=> Simplify miniforge selection script

install-pip-dependencies.sh, install.sh
Maybe fixes Lassen issues 
xref https://github.com/conda/conda/issues/10133 https://github.com/ecisneros8/pyrometheus/pull/26
=> Replace Frankenconda with clean env

install.sh, version.sh
This tiny change set adds the ability to install *MIRGE-Com* from a fork.
=> Add support for mirgecom from forks.

install.sh
Required for https://github.com/illinois-ceesd/mirgecom/pull/525
=> Work around bug in qt package for Python 3.9

install-pip-dependencies.sh
See https://github.com/zheller/flake8-quotes/issues/110
=> limit flake8 version due to flake8-quotes incompatibility

install-pip-dependencies.sh
~~needs~~ benefits from https://github.com/illinois-ceesd/mirgecom/pull/819
Most dev packages already use this, so I think it would be good to have this installed via emirge too.
=> add flake8-comprehensions

.github/workflows/makezip.yaml, .github/workflows/tests.yaml, install.sh
https://github.com/inducer/ci-support/pull/30
https://github.com/conda-forge/pocl-feedstock/pull/96
=> pocl workaround for MacOS

install.sh
https://github.com/conda/conda/issues/13704
=> rename --force to --yes

install-conda.sh
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
=> switch back to miniforge

install.sh
=> make a copy before modifying conda env file
